### ISSUE TITLE
Hey I know this is probably really old, but are some bits of text missing?

### ISSUE THREAD

**Issue by momokotomoko** [hunternet93/OneShot-Dialog-Transcript#1]
I know this is probably really old, but I'm not really seeing things like the part where Niko ask's about the name of your planet in this transcript. That and some others might be missing?

**Comment by hunternet93** [comment]
Sorry it's been so long, I've just [updated the transcript](https://hunternet93.github.io/OneShot-Dialog-Transcript/dialog.html) so it should now have nearly everything. I can't find that one bit you're talking about though, I think the scenes that happen after Niko wakes up in a bed are scripted differently so they don't get picked up during the transcript generation unfortunately.

**Comment by SavannahJohnston** [comment]
Can't you add them manually?
