### ISSUE TITLE
How does one create 'extracted.json'?

### ISSUE THREAD

**Issue by ghost** [hunternet93/OneShot-Dialog-Transcript#2]
Would be useful to know as I'd like to make an up-to-date version of this.

**Comment by hunternet93** [comment]
I just [updated the transcript](https://hunternet93.github.io/OneShot-Dialog-Transcript/dialog.html) from the latest version of the game, I also included some high-level instructions on generating the transcript in the README.

**Comment by ghost** [comment]
Great stuff. Thank you so much!
